name: spaceShootingGame
app_id: da_Ra7IetdUVop0
owner: thewmeme
package: .
scaling:
  mode: single_concurrency
kind: wasmer.io/App.v0
annotations:
  shipitcli.com/config:
    commands: {}
    php_version: 8.3.29
    phpix: true
    phpix_worker_threads: 4
    port: 8080
    use_composer: false
  shipitcli.com/provider: php
  shipitcli.com/version: 0.19.9
